add steps to install codelldb on fedora

diff --git a/run_once_after_06-install-codelldb.sh.tmpl b/run_once_after_06-install-codelldb.sh.tmpl
--- a/run_once_after_06-install-codelldb.sh.tmpl
+++ b/run_once_after_06-install-codelldb.sh.tmpl
@@ -35,4 +35,40 @@ if [ ! -f "$TARGET_FOLDER" ]; then
   cd "$HOME" || exit
 fi
 
+{{ else if eq .osid "linux-fedora" -}}
+
+# Where codelldb files should be stored after initial download
+SOURCE_FOLDER="$HOME/Downloads/codelldb-download"
+
+# Where codelldb files should be placed for cold storage
+TARGET_FOLDER="$HOME/.config/codelldb"
+
+pkg="codelldb-linux-x64.vsix"
+
+if [ ! -f "$TARGET_FOLDER" ]; then
+  # Jump
+  cd "$HOME/Downloads" || exit
+
+  # Download latest codelldb release zip
+  curl -LO "https://github.com/vadimcn/codelldb/releases/latest/download/$pkg"
+
+  # Create source dir
+  mkdir "$SOURCE_FOLDER"
+
+  # Unzip
+  unzip "$pkg" -d "$SOURCE_FOLDER"
+
+  mkdir -p "$TARGET_FOLDER"
+
+  # Copy entire 'extension' folder into ~/.config/codelldb
+  cp -R "$SOURCE_FOLDER/extension" "$TARGET_FOLDER/"
+
+  # Clean up
+  rm -rf "$SOURCE_FOLDER"
+  rm "$pkg"
+
+  # Reset
+  cd "$HOME" || exit
+fi
+
 {{ end -}}
